<?php
/**
 * Extend Warranty - Configurable product warranty offers block
 *
 * @author      Extend Magento Team <magento@guidance.com>
 * @category    Extend
 * @package     Extend_Warranty
 * @copyright   Copyright (c) 2022 Extend Inc. (https://www.extend.com/)
 */
/**
 * @var \Magento\Catalog\Block\Product\View $block
 */

/** @var \Extend\Warranty\ViewModel\Warranty $viewModel */
$viewModel = $block->getData('viewModel');
/** @var string $offerTypeArea */
$offerTypeArea = $block->getData('offerTypeArea');
/** @var \Magento\Catalog\Model\Product $product */
$product = $block->getProduct();

/** @var \Extend\CustomGroupRules\ViewModel\CustomGroupRules $customGroupRules */
$customGroupRules = $block->getData('customGroupRules');
$customerGroupId = (array) $customGroupRules->getCustomerGroupId();
$currentPage = $customGroupRules->getCurrentPage();

?>
<?php if ($viewModel->isExtendEnabled()): ?>
    <?php if (($customGroupRules->isCustomGroupRulesEnabled() == true && empty(array_intersect($customerGroupId, $customGroupRules->getCustomGroupRulesCustomerGroups()))
            && $currentPage == 'catalog_product_view')
        || $customGroupRules->isCustomGroupRulesEnabled() == false

    )  : ?>

    <script type="text/x-magento-init">
    {
        "#product_addtocart_form .box-tocart": {
            "configurableProductWarranty": {
                "isInProductView": true,
                "productId": "<?= $block->escapeJs($product->getId()) ?>",
                "productSku": "warranties_are_only_for_simples",
                "buttonEnabled": <?= $block->escapeJs($viewModel->isProductDetailPageOffersEnabled() ? 1 : 0) ?>,
                "modalEnabled": <?= $block->escapeJs($viewModel->isInterstitialCartOffersEnabled() ? 1 : 0) ?>
            }
        }
    }
    </script>
    <?php endif; ?>

<?php endif; ?>
